#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
#+  Configure HAproxy so that it send traffic to web-01 and web-02
#+  Distribute requests using a roundrobin algorithm
#+   Make sure that HAproxy can be managed via an init script

sudo apt-get -y update
sudo apt install haproxy
HAPROXYCONFIG="
frontend haproxy-main
        bind *:80
        mode http
        default_backend task-servers

backend task-servers
        balance roundrobin
        server 10718-web-01 3.229.113.226:80 check
        server 10718-web-02 44.200.142.76:80 check
"

cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
sudo echo "$HAPROXYCONFIG" >> /etc/haproxy/haproxy.cfg
sudo systemctl restart haproxy.service
