#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

hr=0

while [ $hr -le 12 ]; do
	min=1
	echo "Hour: $hr"
	while [ $min -le 59 ]; do
		echo $min
		min=$((min+1))
	done
	hr=$((hr+1))
done
